version: "3.2"
services:
  bot:
    container_name: sexypizza
    image: ruby:2.3-alpine
    working_dir: /usr/src/app
    command: sh -c "gem update bundler && bundle install && bundle exec ruby main.rb"
    volumes:
      - type: bind
        source: ./main.rb
        target: /usr/src/app/main.rb
      - type: bind
        source: ./Gemfile
        target: /usr/src/app/Gemfile
      - type: bind
        source: ./Gemfile.lock
        target: /usr/src/app/Gemfile.lock
      - type: bind
        source: ./secrets.yaml
        target: /usr/src/app/secrets.yaml
