source "https://rubygems.org"

gem "json"


gem "reddit_bot", "~>1.6.3"
gem "nokogiri"

gem "directlink"

gem "gcplogger", git: "git@github.com:Nakilon/gcplogger.git", tag: "v0.1.1.0"
gem "google-cloud-error_reporting"
