version: "3"
services:
  bot:
    container_name: cptflairbot3
    image: ruby:2.3-alpine
    working_dir: /usr/src/app
    command: sh -c "gem update bundler && apk add git && bundle install && apk add libc6-compat && bundle exec ruby main.rb"
    volumes:
      - type: bind
        source: ./main.rb
        target: /usr/src/app/main.rb
      - type: bind
        source: ./Gemfile
        target: /usr/src/app/Gemfile
      - type: bind
        source: ./Gemfile.lock
        target: /usr/src/app/Gemfile.lock
      - type: bind
        source: ./secrets.yaml
        target: /usr/src/app/secrets.yaml
      - type: bind
        source: ${SECRET_errors_writer_and_logging_writer}
        target: /usr/src/app/keyfile.json
    environment:
      - LOGGING_KEYFILE=keyfile.json
      - TEST
